### ISSUE TITLE
Default Pod port is invalid (8001 vs 5540)

### ISSUE THREAD

**Issue by TheRayquaza** [spy86/redisinsight#3]
Hi 👋 

Within the pod, redis insight listens on 5540:

```
/usr/src/app $ netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5540            0.0.0.0:*               LISTEN      1/node
```

The default port in the template is 8001

```yml
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
```

Possible fix:
* change containerPort to 5540
* customize the `RI_APP_PORT` (https://redis.io/docs/latest/operate/redisinsight/configuration/)
